### ISSUE TITLE
Setup JIRA board and link deeptendies repo

### ISSUE THREAD

**Issue by stancsz** [deep10ds/deeptendies#12]
Refs: 
https://github.com/integrations/jira
https://support.atlassian.com/jira-cloud-administration/docs/integrate-with-github/

**Comment by Karenzhang7717** [comment]
The project board has been set up [here](https://deeptendies.atlassian.net/jira/software/projects/DT/boards/1) 
Will discuss with the team about the roadmap and sprint planning.
